'use client';

import * as React from 'react';
import { useState, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { PencilLine, Users, Lightbulb, ListChecks, AlertCircle, Sparkles } from 'lucide-react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ReportSection as ReportSectionType } from '@/lib/types';
import { useReportStore } from '@/lib/store';

const iconMap = {
  AlertCircle: AlertCircle,
  Users: Users,
  Lightbulb: Lightbulb,
  ListChecks: ListChecks,
};

export function ReportSection({ section }: { section: ReportSectionType }) {
  const { setEditingSection, setHighlightedText, report } = useReportStore();
  const IconComponent = iconMap[section.icon as keyof typeof iconMap] || AlertCircle;
  const versionCount = report?.versions.filter(v => v.sectionId === section.id).length || 0;
  
  const [popupPos, setPopupPos] = useState<{ top: number, left: number } | null>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  // Handle Text Selection
  const handleMouseUp = (e: React.MouseEvent) => {
    // If we are clicking the floating button itself, do nothing!
    if ((e.target as HTMLElement).closest('#ai-float-btn')) return;

    setTimeout(() => {
      const selection = window.getSelection();
      if (!selection || selection.isCollapsed || selection.toString().trim() === '') {
        setPopupPos(null);
        return;
      }

      if (contentRef.current && contentRef.current.contains(selection.anchorNode)) {
        const range = selection.getRangeAt(0);
        const rect = range.getBoundingClientRect();
        
        setPopupPos({
          top: rect.top - 55, 
          left: rect.left + (rect.width / 2) - 50,
        });
      }
    }, 10);
  };

  // CRITICAL FIX: Use onMouseDown and stop propagation
  const handleHighlightEdit = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation(); // Prevents the mouse event from bubbling up and causing a loop

    const selection = window.getSelection();
    const text = selection ? selection.toString().trim() : '';

    if (text) {
      setHighlightedText(text);
      setEditingSection(section.id);
      setPopupPos(null);
    }
  };

  // Clear popup when clicking away
  useEffect(() => {
    const hidePopup = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest('#ai-float-btn')) {
        setPopupPos(null);
      }
    };
    document.addEventListener('mousedown', hidePopup);
    return () => document.removeEventListener('mousedown', hidePopup);
  }, []);

  return (
    <div className="relative">
      {/* Floating AI Edit Button */}
      {popupPos && (
        <div 
          id="ai-float-btn"
          className="fixed z-[9999] animate-in fade-in zoom-in-95 duration-200 drop-shadow-2xl"
          style={{ top: popupPos.top, left: popupPos.left }}
        >
          {/* Changed to onMouseDown for instant response without bubbling */}
          <Button 
            onMouseDown={handleHighlightEdit} 
            size="sm" 
            className="gap-2 bg-slate-900 text-white hover:bg-slate-800 rounded-full h-10 px-5 shadow-xl border border-slate-700 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-purple-400" /> AI Edit
          </Button>
        </div>
      )}

      <Card className="mb-8 overflow-hidden border-slate-200 bg-white shadow-sm transition-all group">
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4 border-b border-slate-100 bg-slate-50/50">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-primary/10 text-primary rounded-lg ring-1 ring-primary/20">
              <IconComponent className="w-5 h-5" />
            </div>
            <div>
              <CardTitle className="text-xl font-bold tracking-tight text-slate-900">
                {section.title}
              </CardTitle>
              <div className="flex items-center space-x-2 mt-1">
                <Badge variant="secondary" className="text-xs font-normal border-primary/20 bg-primary/5 text-primary">
                  Generated by {section.agentSource} agent
                </Badge>
                {versionCount > 0 && (
                  <Badge variant="outline" className="text-xs font-normal text-slate-500 border-slate-200 bg-white">
                    {versionCount} AI edit{versionCount > 1 ? 's' : ''}
                  </Badge>
                )}
              </div>
            </div>
          </div>
          
          <Button 
            variant="outline" size="sm" 
            className="h-9 gap-2 shadow-sm bg-white hover:bg-slate-50 border-slate-200 text-slate-700"
            onClick={() => {
              setHighlightedText(null); 
              setEditingSection(section.id);
            }}
          >
            <PencilLine className="w-4 h-4" /> Edit Full Section
          </Button>
        </CardHeader>
        
        <CardContent 
          ref={contentRef}
          onMouseUp={handleMouseUp}
          className="pt-8 pb-8 prose prose-slate max-w-none cursor-text selection:bg-purple-200 selection:text-purple-900"
        >
          <div className="markdown-body">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {section.content}
            </ReactMarkdown>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}