'use client';

import * as React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { PencilLine, Beaker, CheckCircle2, ListChecks, Users, Lightbulb, AlertCircle } from 'lucide-react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ReportSection as ReportSectionType } from '@/lib/types';
import { useReportStore } from '@/lib/store';

const iconMap = {
  AlertCircle: AlertCircle,
  Users: Users,
  Lightbulb: Lightbulb,
  ListChecks: ListChecks,
};

interface ReportSectionProps {
  section: ReportSectionType;
}

export function ReportSection({ section }: ReportSectionProps) {
  const setEditingSection = useReportStore((state) => state.setEditingSection);
  const report = useReportStore((state) => state.report);

  const IconComponent = iconMap[section.icon as keyof typeof iconMap] || AlertCircle;
  
  // Find versions for this section
  const versionCount = report?.versions.filter(v => v.sectionId === section.id).length || 0;

  return (
    <Card className="mb-6 overflow-hidden border-border/50 bg-card/50 backdrop-blur-xl shadow-lg transition-all hover:shadow-xl group relative">
      {/* Decorative gradient border effect */}
      <div className="absolute inset-0 bg-gradient-to-r from-primary/10 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
      
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4 border-b border-border/30 bg-muted/20">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-primary/10 text-primary rounded-lg ring-1 ring-primary/20">
            <IconComponent className="w-5 h-5" />
          </div>
          <div>
            <CardTitle className="text-xl font-bold tracking-tight">
              {section.title}
            </CardTitle>
            <div className="flex items-center space-x-2 mt-1">
              <Badge variant="secondary" className="text-xs font-normal border-primary/20 bg-primary/5 text-primary">
                Generated by {section.agentSource} agent
              </Badge>
              {versionCount > 0 && (
                <Badge variant="outline" className="text-xs font-normal text-muted-foreground border-border/50">
                  {versionCount} AI edit{versionCount > 1 ? 's' : ''}
                </Badge>
              )}
            </div>
          </div>
        </div>
        
        <Button 
          variant="outline" 
          size="sm" 
          className="h-9 gap-2 shadow-sm bg-background/50 hover:bg-primary/5 hover:text-primary transition-colors border-border/50"
          onClick={() => setEditingSection(section.id)}
        >
          <PencilLine className="w-4 h-4" />
          Edit with AI
        </Button>
      </CardHeader>
      
      <CardContent className="pt-6 prose prose-neutral dark:prose-invert max-w-none">
        <div className="markdown-body">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {section.content}
          </ReactMarkdown>
        </div>
      </CardContent>
    </Card>
  );
}
