import { NextResponse } from 'next/server';
import { 
  Document, Paragraph, TextRun, HeadingLevel, Packer, 
  BorderStyle, Table, TableRow, TableCell, WidthType, 
  ShadingType, AlignmentType, TableLayoutType, ImageRun
} from 'docx';
import { ExportRequest, ReportSection } from '@/lib/types';
import { marked } from 'marked';
import { sanitizeMarkdown } from '@/lib/markdown/sanitize';

export const maxDuration = 30;

const renderInlineTokens = (tokens: any[] = [], colorOverride?: string, forceBold: boolean = false) => {
  return tokens.map((t: any) => {
    const isBold = t.type === 'strong';
    const isItalic = t.type === 'em';
    
    let content = "";
    if (t.tokens && t.tokens.length > 0) {
       content = t.tokens.map((child: any) => child.text || child.raw || "").join('');
    } else {
       content = t.text || t.raw || "";
    }

    content = content
      .replace(/\*\*/g, '') 
      .replace(/\*/g, '')   
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&amp;/g, '&');
    
    return new TextRun({
      text: content,
      bold: forceBold || isBold,
      italics: isItalic,
      size: 22,
      color: colorOverride || (isBold ? "000000" : "333333"), 
    });
  });
};

export async function POST(req: Request) {
  try {
    const { report } = (await req.json()) as ExportRequest;

    if (!report) {
      return NextResponse.json(
        { error: 'Report data is required' },
        { status: 400 }
      );
    }

    const createDocxContent = (sections: ReportSection[]) => {
      const docChildren: any[] = [];
      
      docChildren.push(
        new Paragraph({
          text: 'Strategic Execution Plan',
          heading: HeadingLevel.TITLE,
          spacing: { after: 400, before: 4000 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({
          text: 'Generated by ForceEqual AI',
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 1200 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({
          text: 'Problem Statement:',
          heading: HeadingLevel.HEADING_3,
          spacing: { after: 200 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: report.problemStatement, italics: true, size: 24 })
          ],
          spacing: { after: 800 },
          border: {
            left: { color: '6366F1', space: 10, size: 20, style: BorderStyle.SINGLE }
          }
        }),
        new Paragraph({
          text: `Generated on: ${new Date(report.createdAt).toLocaleDateString()}`,
          spacing: { before: 2000 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({ pageBreakBefore: true })
      );

      sections.forEach((section) => {
        docChildren.push(
          new Paragraph({
            text: section.title,
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 300 }
          })
        );
        
        const normalizedContent = sanitizeMarkdown(section.content);
        const lines = normalizedContent.split('\n');
        const fixedLines = [];
        let inTable = false;

        for (let i = 0; i < lines.length; i++) {
          const line = lines[i].trim();
          const isTableLine = line.startsWith('|');
          
          if (isTableLine && !inTable) {
            fixedLines.push(''); 
            inTable = true;
          } else if (!isTableLine && inTable) {
            fixedLines.push(''); 
            inTable = false;
          }
          fixedLines.push(lines[i]);
        }

        const cleanMarkdown = fixedLines.join('\n');
        const tokens = marked.lexer(cleanMarkdown, { gfm: true });
        
        let diagramIndex = 0;
        
        tokens.forEach((token: any) => {
          if (token.type === 'code' && token.lang === 'mermaid') {
             const imgArr = (section as any).diagramImages;
             if (imgArr && imgArr[diagramIndex]) {
               const imgData = imgArr[diagramIndex];
               const base64Data = imgData.base64.split('base64,')[1];
               
               const targetWidth = Math.min(600, imgData.width);
               const targetHeight = (imgData.height / imgData.width) * targetWidth;

               docChildren.push(
                 new Paragraph({
                   children: [
                     new ImageRun({
                       data: Buffer.from(base64Data, "base64"),
                       transformation: { width: targetWidth, height: targetHeight },
                       type: "png"
                     })
                   ],
                   alignment: AlignmentType.CENTER,
                   spacing: { before: 400, after: 400 }
                 })
               );
             }
             diagramIndex++;
          }
          else if (token.type === 'heading') {
            const hLevel = 
              token.depth === 1 ? HeadingLevel.HEADING_1 :
              token.depth === 2 ? HeadingLevel.HEADING_2 :
              token.depth === 3 ? HeadingLevel.HEADING_3 :
              HeadingLevel.HEADING_4;
              
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                heading: hLevel,
                spacing: { before: 300, after: 150 }
              })
            );
          } 
          else if (token.type === 'paragraph') {
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                spacing: { after: 200 }
              })
            );
          } 
          else if (token.type === 'list') {
            token.items.forEach((item: any) => {
              docChildren.push(
                new Paragraph({
                  children: renderInlineTokens(item.tokens),
                  bullet: { level: 0 },
                  spacing: { after: 150 }
                })
              );
            });
            docChildren.push(new Paragraph({ spacing: { after: 100 } })); 
          } 
          else if (token.type === 'blockquote') {
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                spacing: { after: 200 },
                border: {
                  left: { color: '8B5CF6', space: 10, size: 15, style: BorderStyle.SINGLE }
                }
              })
            );
          }
          else if (token.type === 'table') {
            const tableRows: TableRow[] = [];
            
            const headerCells = token.header.map((cell: any) => {
              return new TableCell({
                children: [
                  new Paragraph({ 
                    children: renderInlineTokens(cell.tokens, "FFFFFF", true), 
                    alignment: AlignmentType.CENTER 
                  })
                ],
                shading: { fill: "7C3AED", type: ShadingType.CLEAR, color: "auto" }, 
                margins: { top: 100, bottom: 100, left: 100, right: 100 }
              });
            });
            tableRows.push(new TableRow({ children: headerCells, tableHeader: true }));

            token.rows.forEach((row: any) => {
              const rowCells = row.map((cell: any) => {
                return new TableCell({
                  children: [new Paragraph({ children: renderInlineTokens(cell.tokens) })],
                  margins: { top: 100, bottom: 100, left: 100, right: 100 }
                });
              });
              tableRows.push(new TableRow({ children: rowCells }));
            });

            // ADDED AUTOFIT LAYOUT to stop tables getting cut off
            docChildren.push(
              new Table({
                rows: tableRows,
                width: { size: 100, type: WidthType.PERCENTAGE },
                layout: TableLayoutType.AUTOFIT, 
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  left: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  right: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                }
              })
            );
            docChildren.push(new Paragraph({ spacing: { after: 300 } })); 
          }
        });
        
        docChildren.push(new Paragraph({ text: '', spacing: { after: 400 } }));
      });

      return docChildren;
    };

    const doc = new Document({
      creator: 'ForceEqual AI',
      title: 'Strategic Execution Plan',
      description: 'Strategic plan report generated by multi-agent pipeline',
      sections: [
        {
          // REDUCED MARGINS to give tables more horizontal room in Word
          properties: {
            page: {
              margin: {
                top: 1000,
                right: 800,
                bottom: 1000,
                left: 800,
              },
            },
          },
          children: createDocxContent(report.sections),
        },
      ],
    });

    const b64string = await Packer.toBase64String(doc);
    
    return NextResponse.json({ 
      success: true, 
      base64: b64string,
      filename: `Strategic_Plan_${new Date().getTime()}.docx`
    });

  } catch (error) {
    console.error('DOCX Export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate DOCX' },
      { status: 500 }
    );
  }
}