import { NextResponse } from 'next/server';
import { Document, Paragraph, TextRun, HeadingLevel, Packer, BorderStyle } from 'docx';
import { ExportRequest, ReportSection } from '@/lib/types';
import { marked } from 'marked';

export const maxDuration = 30;

export async function POST(req: Request) {
  try {
    const { report } = (await req.json()) as ExportRequest;

    if (!report) {
      return NextResponse.json(
        { error: 'Report data is required' },
        { status: 400 }
      );
    }

    // Convert markdown to docx paragraphs
    const createDocxContent = (sections: ReportSection[]) => {
      const docChildren: any[] = [];
      
      // Title Page
      docChildren.push(
        new Paragraph({
          text: 'AI Strategic Plan',
          heading: HeadingLevel.TITLE,
          spacing: { after: 400, before: 4000 },
          alignment: 'center'
        }),
        new Paragraph({
          text: 'Generated by ForceEqual AI',
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 1200 },
          alignment: 'center'
        }),
        new Paragraph({
          text: 'Problem Statement:',
          heading: HeadingLevel.HEADING_3,
          spacing: { after: 200 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: report.problemStatement, italics: true, size: 24 })
          ],
          spacing: { after: 800 },
          border: {
            left: { color: 'CCCCCC', space: 10, size: 20, style: BorderStyle.SINGLE }
          }
        }),
        new Paragraph({
          text: `Generated on: ${new Date(report.createdAt).toLocaleDateString()}`,
          spacing: { before: 2000 },
          alignment: 'center'
        }),
        new Paragraph({ pageBreakBefore: true })
      );

      // We process each section by parsing its markdown
      sections.forEach((section) => {
        // Section Title
        docChildren.push(
          new Paragraph({
            text: section.title,
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          })
        );
        
        // Very basic markdown parsing for DOCX structure
        const tokens = marked.lexer(section.content);
        
        tokens.forEach((token) => {
          if (token.type === 'heading') {
            const hLevel = 
              token.depth === 1 ? HeadingLevel.HEADING_1 :
              token.depth === 2 ? HeadingLevel.HEADING_2 :
              token.depth === 3 ? HeadingLevel.HEADING_3 :
              HeadingLevel.HEADING_4;
              
            docChildren.push(
              new Paragraph({
                text: token.text,
                heading: hLevel,
                spacing: { before: 200, after: 100 }
              })
            );
          } else if (token.type === 'paragraph') {
            // Strip strong/em for simple parsing, but we can do a basic check
            docChildren.push(
              new Paragraph({
                children: [new TextRun({ text: token.text, size: 22 })],
                spacing: { after: 150 }
              })
            );
          } else if (token.type === 'list') {
            token.items.forEach((item: any) => {
              docChildren.push(
                new Paragraph({
                  children: [new TextRun({ text: item.text, size: 22 })],
                  bullet: { level: 0 },
                  spacing: { after: 100 }
                })
              );
            });
          } else if (token.type === 'space') {
            // ignore
          } else {
            // fallback for other entities
            docChildren.push(
              new Paragraph({
                children: [new TextRun({ text: token.raw, size: 22 })],
                spacing: { after: 150 }
              })
            );
          }
        });
        
        // Add a line break after each section
        docChildren.push(new Paragraph({ text: '', spacing: { after: 400 } }));
      });

      return docChildren;
    };

    const doc = new Document({
      creator: 'ForceEqual AI',
      title: 'AI Strategic Plan',
      description: 'Strategic plan report generated by AI',
      sections: [
        {
          properties: {},
          children: createDocxContent(report.sections),
        },
      ],
    });

    const b64string = await Packer.toBase64String(doc);
    
    return NextResponse.json({ 
      success: true, 
      base64: b64string,
      filename: `Report-${new Date().getTime()}.docx`
    });

  } catch (error) {
    console.error('DOCX Export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate DOCX' },
      { status: 500 }
    );
  }
}
