import { NextResponse } from 'next/server';
import { 
  Document, Paragraph, TextRun, HeadingLevel, Packer, 
  BorderStyle, Table, TableRow, TableCell, WidthType, 
  ShadingType, AlignmentType 
} from 'docx';
import { ExportRequest, ReportSection } from '@/lib/types';
import { marked } from 'marked';

export const maxDuration = 30;

// Helper to parse inline markdown and aggressively strip asterisks
const renderInlineTokens = (tokens: any[] = []) => {
  return tokens.map((t: any) => {
    const isBold = t.type === 'strong';
    const isItalic = t.type === 'em';
    
    let content = "";
    if (t.tokens && t.tokens.length > 0) {
       content = t.tokens.map((child: any) => child.text || child.raw || "").join('');
    } else {
       content = t.text || t.raw || "";
    }

    // Aggressively clean leftover markdown and HTML entities
    content = content
      .replace(/\*\*/g, '') 
      .replace(/\*/g, '')   
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&amp;/g, '&');
    
    return new TextRun({
      text: content,
      bold: isBold,
      italics: isItalic,
      size: 22,
      color: isBold ? "000000" : "333333", // Black for bold, dark gray for normal
    });
  });
};

export async function POST(req: Request) {
  try {
    const { report } = (await req.json()) as ExportRequest;

    if (!report) {
      return NextResponse.json(
        { error: 'Report data is required' },
        { status: 400 }
      );
    }

    const createDocxContent = (sections: ReportSection[]) => {
      const docChildren: any[] = [];
      
      // Title Page
      docChildren.push(
        new Paragraph({
          text: 'Strategic Execution Plan',
          heading: HeadingLevel.TITLE,
          spacing: { after: 400, before: 4000 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({
          text: 'Generated by ForceEqual AI',
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 1200 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({
          text: 'Problem Statement:',
          heading: HeadingLevel.HEADING_3,
          spacing: { after: 200 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: report.problemStatement, italics: true, size: 24 })
          ],
          spacing: { after: 800 },
          border: {
            left: { color: '6366F1', space: 10, size: 20, style: BorderStyle.SINGLE }
          }
        }),
        new Paragraph({
          text: `Generated on: ${new Date(report.createdAt).toLocaleDateString()}`,
          spacing: { before: 2000 },
          alignment: AlignmentType.CENTER
        }),
        new Paragraph({ pageBreakBefore: true })
      );

      // Process each section
      sections.forEach((section) => {
        // Section Title
        docChildren.push(
          new Paragraph({
            text: section.title,
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 300 }
          })
        );
        
        // --- 100% FOOLPROOF TABLE FIX ---
        // Manually parse line by line to guarantee blank lines around tables
        const lines = section.content.split('\n');
        const fixedLines = [];
        let inTable = false;

        for (let i = 0; i < lines.length; i++) {
          const line = lines[i].trim();
          const isTableLine = line.startsWith('|');
          
          if (isTableLine && !inTable) {
            fixedLines.push(''); // Force a blank line BEFORE the table starts
            inTable = true;
          } else if (!isTableLine && inTable) {
            fixedLines.push(''); // Force a blank line AFTER the table ends
            inTable = false;
          }
          fixedLines.push(lines[i]);
        }

        const cleanMarkdown = fixedLines.join('\n');
        
        // Parse the cleaned markdown with GFM enabled to read tables
        const tokens = marked.lexer(cleanMarkdown, { gfm: true });
        
        tokens.forEach((token: any) => {
          if (token.type === 'heading') {
            const hLevel = 
              token.depth === 1 ? HeadingLevel.HEADING_1 :
              token.depth === 2 ? HeadingLevel.HEADING_2 :
              token.depth === 3 ? HeadingLevel.HEADING_3 :
              HeadingLevel.HEADING_4;
              
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                heading: hLevel,
                spacing: { before: 300, after: 150 }
              })
            );
          } 
          else if (token.type === 'paragraph') {
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                spacing: { after: 200 }
              })
            );
          } 
          else if (token.type === 'list') {
            token.items.forEach((item: any) => {
              docChildren.push(
                new Paragraph({
                  children: renderInlineTokens(item.tokens),
                  bullet: { level: 0 },
                  spacing: { after: 150 }
                })
              );
            });
            docChildren.push(new Paragraph({ spacing: { after: 100 } })); // spacer
          } 
          else if (token.type === 'blockquote') {
            docChildren.push(
              new Paragraph({
                children: renderInlineTokens(token.tokens),
                spacing: { after: 200 },
                border: {
                  left: { color: '8B5CF6', space: 10, size: 15, style: BorderStyle.SINGLE }
                }
              })
            );
          }
          else if (token.type === 'table') {
            const tableRows: TableRow[] = [];
            
            // 1. Table Header (Colored Background)
            const headerCells = token.header.map((cell: any) => {
              return new TableCell({
                children: [
                  new Paragraph({ 
                    children: renderInlineTokens(cell.tokens).map(tr => {
                      tr.color = "FFFFFF"; // White text for header
                      tr.bold = true;
                      return tr;
                    }), 
                    alignment: AlignmentType.CENTER 
                  })
                ],
                shading: { fill: "7C3AED", type: ShadingType.CLEAR, color: "auto" }, // Primary Purple
                margins: { top: 100, bottom: 100, left: 100, right: 100 }
              });
            });
            tableRows.push(new TableRow({ children: headerCells, tableHeader: true }));

            // 2. Table Body Rows
            token.rows.forEach((row: any) => {
              const rowCells = row.map((cell: any) => {
                return new TableCell({
                  children: [new Paragraph({ children: renderInlineTokens(cell.tokens) })],
                  margins: { top: 100, bottom: 100, left: 100, right: 100 }
                });
              });
              tableRows.push(new TableRow({ children: rowCells }));
            });

            docChildren.push(
              new Table({
                rows: tableRows,
                width: { size: 100, type: WidthType.PERCENTAGE },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  left: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  right: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                  insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
                }
              })
            );
            docChildren.push(new Paragraph({ spacing: { after: 300 } })); // spacer after table
          }
        });
        
        // Add a line break after each full section
        docChildren.push(new Paragraph({ text: '', spacing: { after: 400 } }));
      });

      return docChildren;
    };

    const doc = new Document({
      creator: 'ForceEqual AI',
      title: 'Strategic Execution Plan',
      description: 'Strategic plan report generated by multi-agent pipeline',
      sections: [
        {
          properties: {},
          children: createDocxContent(report.sections),
        },
      ],
    });

    const b64string = await Packer.toBase64String(doc);
    
    return NextResponse.json({ 
      success: true, 
      base64: b64string,
      filename: `Strategic_Plan_${new Date().getTime()}.docx`
    });

  } catch (error) {
    console.error('DOCX Export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate DOCX' },
      { status: 500 }
    );
  }
}